version: "2"

linters:
  default: all
  disable:
    - cyclop    # revive
    - funlen    # revive
    - gocognit  # revive
    - gocyclo   # revive
    - lll       # revive

    - dupl
    - err113
    - exhaustruct
    - gochecknoglobals
    - goconst
    - godox
    - gosec
    - ireturn
    - maintidx
    - mnd
    - nlreturn
    - paralleltest
    - tagliatelle
    - testpackage
    - unparam
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
    - funcorder
  settings:

    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/pkg/errors
              desc: errors.Wrap() is deprecated in favor of fmt.Errorf()

    errcheck:
      check-type-assertions: false

    gocritic:
      enable-all: true
      disabled-checks:
        - appendCombine
        - paramTypeCombine
        - sloppyReassign
        - unnamedResult
        - importShadow

    govet:
      disable:
        - fieldalignment
      enable-all: true

    misspell:
      locale: US

    nestif:
      # lower this after refactoring
      min-complexity: 13

    nlreturn:
      block-size: 4

    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false

    revive:
      severity: error
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: cognitive-complexity
          arguments:
            # lower this after refactoring
            - 49
        - name: comment-spacings
          disabled: true
        - name: confusing-results
          disabled: true
        - name: cyclomatic
          arguments:
            # lower this after refactoring
            - 28
        - name: flag-parameter
          disabled: true
        - name: function-length
          arguments:
            # lower this after refactoring
            - 74
            - 149
        - name: import-alias-naming
          disabled: true
        - name: import-shadowing
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: nested-structs
          disabled: true
        - name: exported
          disabled: true
        - name: unexported-return
          disabled: true
        - name: unhandled-error
          arguments:
            - fmt.Print
            - fmt.Printf
            - fmt.Println
        - name: function-result-limit
          arguments:
            - 5
    staticcheck:
      checks:
        - all
    wsl:
      allow-trailing-comment: true
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        text: 'shadow: declaration of "(err|ctx)" shadows declaration'

      - linters:
          - perfsprint
        text: fmt.Sprintf can be replaced .*
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/crowdsecurity)
        - prefix(github.com/crowdsecurity/crowdsec)
        - prefix(github.com/crowdsecurity/cs-firewall-bouncer)
  exclusions:
    paths:
      - third_party$
      - builtin$
      - examples$
