name: build-binary-package

on:
  release:
    types:
    - prereleased

permissions:
  # Use write for: hub release edit
  contents: write

env:
  PROGRAM_NAME: crowdsec-firewall-bouncer

jobs:
  build:
    name: Build and upload all platforms
    runs-on: ubuntu-latest

    steps:

    - name: Check out repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version-file: go.mod

    - name: Build all platforms
      run: |
        # build platform-all first so the .xz vendor file is not removed
        make platform-all vendor

    - name: Upload to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag_name="${GITHUB_REF##*/}"
        # this will upload the $PROGRAM_NAME-vendor.tar.xz file as well
        gh release upload "$tag_name" $PROGRAM_NAME* vendor.tgz
