# .github/workflows/build-docker-image.yml
name: build-binary-package

on: 
  release:
    types: prereleased

jobs:
  build-binary-package:
    name: Build and upload binary package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
            {"goarch": "386", "arch": "i386", "goarm": ""},
            {"goarch": "arm64", "arch": "aarch64", "goarm": ""},
            {"goarch": "arm", "arch": "armv7", "goarm": "7"},
            {"goarch": "arm", "arch": "armhf", "goarm": "6"},
            {"goarch": "amd64", "arch": "amd64", "goarm": ""}
          ]
    steps:
    - name: Set up Go 1.19
      uses: actions/setup-go@v1
      with:
        go-version: 1.19
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build ${{ matrix.target.arch }} binaries
      env:
        GOARCH: ${{ matrix.target.goarch }}
        GOARM: ${{ matrix.target.goarm }}
      run: make release
    - name: Rename .tgz
      run: mv crowdsec-firewall-bouncer.tgz crowdsec-firewall-bouncer-${{ matrix.target.arch }}.tgz
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: crowdsec-firewall-bouncer-${{ matrix.target.arch }}.tgz application/x-gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
