name: build-binary-package

on:
  release:
    types:
    - prereleased

permissions:
  # Use write for: hub release edit
  contents: write

env:
  PROGRAM_NAME: crowdsec-firewall-bouncer

jobs:
  build:
    name: Build and upload all platforms
    runs-on: ubuntu-latest

    steps:

    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.7

    - name: Build all platforms
      run: |
        # build platform-all first so the .xz vendor file is not removed
        make platform-all vendor

    - name: Upload to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag_name="${GITHUB_REF##*/}"
        # this will find the $PROGRAM_NAME-vendor.tar.xz file as well
        hub release edit $(find . -name "$PROGRAM_NAME*" -maxdepth 1 -printf "-a %p ") -a vendor.tgz -m "" "$tag_name"
