name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.20.1
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.1

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build
      run: make build

    - name: Test
      run: go test -v

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.51
        args: --issues-exit-code=1 --timeout 10m
        only-new-issues: false
