name: Static Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    name: "golangci-lint + codeql"
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: go, python

    - name: Build
      run: |
        make build

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.61
        args: --issues-exit-code=1 --timeout 10m
        only-new-issues: false

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
