name: Static Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    name: "golangci-lint + codeql"
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.6

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: go, python

    - name: Build
      run: |
        make build

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.55
        args: --issues-exit-code=1 --timeout 10m
        only-new-issues: false
        # the cache is already managed above, enabling it here
        # gives errors when extracting
        skip-pkg-cache: true
        skip-build-cache: true

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
